tasks:
  - init: |
      echo '==> Install deps'
      sudo apt-get update
      sudo apt-get install -y build-essential libncurses5-dev bzip2
      sudo apt-get install repo
      sudo apt-get install git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 libncurses5 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig
    command: |
      echo 'TODO: start app'